### ISSUE TITLE
Configure Linting and Code Formatting Tools

### ISSUE THREAD

**Issue by AhmedRaisi** [AhmedRaisi/Tarsho#11]
Title: Set Up ESLint and Prettier for the Project

Description:
Consistent coding styles and standards are crucial for a collaborative project. Set up ESLint for linting and Prettier for code formatting.

Acceptance Criteria:

ESLint is configured with a set of agreed-upon rules.
Prettier is configured for code formatting.
Pre-commit hooks are set up to run linting and formatting.

**Comment by AhmedRaisi** [comment]
not important now moved to testing stage

**Comment by Bateyjosue** [comment]
Hey @AhmedRaisi, I would like to work on this

**Comment by AhmedRaisi** [comment]
@Bateyjosue No problem at all, add me on discord, rrolle and we can meet and ill help you set everything up. I want to know what errors everybody is encountering.
