### ISSUE TITLE
Issue 1: Setup Welcome Page with Link to Login Page

### ISSUE THREAD

**Issue by AhmedRaisi** [AhmedRaisi/Tarsho#18]
Objective: Create an initial welcome or landing page for the application with a link to the login page.

Tasks:

Design a simple welcome page layout.
Include a prominent link or button to navigate to the login page.
Implement responsive design for various screen sizes.
Test the navigation from the welcome page to the login page.

**Comment by alhos011** [comment]
Done Ig
