### ISSUE TITLE
Make Distinguishable Login and Logout Button in Header

### ISSUE THREAD

**Issue by AhmedRaisi** [AhmedRaisi/Tarsho#52]
Description:
Enhance the visual distinction of the login button in the header to make it stand out from other navigation links.

Details:
Suggestions include changing button color, adding an icon, or altering its size.

**Comment by AhmedRaisi** [comment]
Description:
Objective: Improve the visibility and distinction of the login button in the header navigation to enhance user experience.
Details: The login button should be easily distinguishable from other navigation links.
Suggested Implementation: Use a different color, style, or add an icon to the login button to make it stand out.

**Comment by 24kushang** [comment]
I would like to fix this issue. Please assign it to me

**Comment by AhmedRaisi** [comment]
> Can I work on this issue as well @AhmedRaisi 
> 
> 

Yes

**Comment by 24kushang** [comment]
@AhmedRaisi I was halfway there in fixing this issue
