### ISSUE TITLE
Refine Login and Register Method on Homepage

### ISSUE THREAD

**Issue by AhmedRaisi** [AhmedRaisi/Tarsho#96]
Reconfigure the login method on the homepage to be more user-friendly and intuitive, enhancing the overall user experience.
Acceptance Criteria:
Login method is user-friendly and intuitive.
Clear instructions and feedback for users during the login process.

**Comment by last-hop** [comment]
hello @AhmedRaisi  I want to work on this will you assign it to me please ?

**Comment by last-hop** [comment]
I  have made few changes in the login page if you think its good enough then I can start doing it on Register as well
![Screenshot 2023-12-01 120206](https://github.com/AhmedRaisi/Tarsho/assets/85928582/fb391eba-53c0-4da8-9bca-7f100c69e2db)

**Comment by AhmedRaisi** [comment]
I like it, if you can make the the register modal similar and maybe do something about how the create an account message looks.

**Comment by AhmedRaisi** [comment]
> I  have made few changes in the login page if you think its good enough then I can start doing it on Register as well
> 
> I have adjusted the alignment of button ,added a placeholder , added a link to register page and some size changes 
> 
> ![Screenshot 2023-12-01 120206](https://github.com/AhmedRaisi/Tarsho/assets/85928582/fb391eba-53c0-4da8-9bca-7f100c69e2db)
> 
> 

I like it, if you can make the the register modal similar and maybe do something about how the create an account message looks.

**Comment by AhmedRaisi** [comment]
> I am updating code now if you want any changes let me know

please pull latest i made some ui/ux adjustments

**Comment by AhmedRaisi** [comment]
Thank you @last-hop
